#!/usr/bin/env bash
#
# Borealis Linux — ISO build orchestrator
# ---------------------------------------
# Produces: borealis-<version>-amd64.iso (hybrid BIOS+UEFI)
#
# Requirements: Debian 12/13 host (bare metal, VM, or WSL2) with sudo.
# Run scripts/bootstrap-host.sh first (idempotent), or let this script do it.
#
# Environment overrides:
#   ISO_VERSION=1.0              version string in image name / os-release
#   SKIP_OPTIONAL=1              skip optional-verified packages entirely
#   KEEP_CACHE=1                 keep lb cache between builds (faster rebuilds)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

ISO_VERSION="${ISO_VERSION:-1.0}"
DIST=bookworm
ARCH=amd64
# Build-time mirror (bootstrap+chroot download). The shipped image keeps
# deb.debian.org as its sources list — end users are unaffected.
MIRROR="${MIRROR:-http://deb.debian.org/debian}"
LOG="$ROOT/borealis-build.log"

say()  { printf '\033[1;36m[build]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[build: FATAL]\033[0m %s\n' "$*" >&2; exit 1; }

# live-build's chroot stages need root; privileged containers (CI) run us as
# root directly, developer hosts go through sudo.
SUDO=""
if [[ $EUID -ne 0 ]]; then
    SUDO="sudo"
fi

# --- 0. host sanity -----------------------------------------------------------
if ! grep -qE 'ID=debian|ID_LIKE=.*debian' /etc/os-release 2>/dev/null; then
    die "Build host must be Debian 12/13 (bare, VM, or WSL2). Current OS is not Debian."
fi
say "Ensuring build tools (scripts/bootstrap-host.sh)"
$SUDO scripts/bootstrap-host.sh

# --- 1. verify optional packages against apt metadata -------------------------
say "Verifying package availability (prevents mid-build aborts)"
python3 - <<'PYEOF'
import os, subprocess, sys
opt = "config/package-lists/borealis-optional.list.chroot.template"
out = "config/package-lists/zz-optional-verified.list.chroot"
if os.environ.get("SKIP_OPTIONAL") == "1":
    open(out, "w").close()
    sys.exit(0)
pkgs = []
with open(opt) as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith("#"):
            pkgs.append(line)
missing, present = [], []
for p in pkgs:
    r = subprocess.run(["apt-cache", "show", p], capture_output=True)
    (present if r.returncode == 0 or r.stdout else missing).append(p)
with open(out, "w") as f:
    f.write("# Auto-generated by build.sh — do not edit\n")
    f.writelines(x + "\n" for x in present)
print(f"  optional: {len(present)} available, {len(missing)} skipped")
if missing:
    print("  skipped (not in repos on this host): " + ", ".join(missing))
PYEOF

# Core list must be fully resolvable — abort early with a clear message.
for pkg in $(grep -hvE '^\s*(#|$)' config/package-lists/borealis-base.list.chroot); do
    if ! apt-cache show "$pkg" >/dev/null 2>&1; then
        die "Core package '$pkg' not found in apt metadata — check borealis-base.list.chroot"
    fi
done
say "Core package list OK"

# --- 2. sync custom sources into the image overlay ----------------------------
say "Syncing apps, installer config into the image overlay"
install -d config/includes.chroot/usr/bin \
            config/includes.chroot/usr/lib/borealis \
            config/includes.chroot/usr/share/borealis/themes \
            config/includes.chroot/etc/calamares
install -m 0755 src/apps/borealis-store src/apps/borealis-settings \
                src/apps/borealis-quick src/apps/borealis-welcome \
        config/includes.chroot/usr/bin/
install -m 0644 src/lib/borealis_common.py \
        config/includes.chroot/usr/lib/borealis/borealis_common.py
cp -r calamares/. config/includes.chroot/etc/calamares/

# --- 3. generate artwork (wallpapers, logos, branding, skel theme wiring) ------
say "Generating artwork (wallpapers, logo, previews)"
python3 scripts/generate-artwork.py --root "$ROOT" || die "artwork generation failed"

# themes carry their generated wallpapers — copy after artwork step
say "Syncing themes into the image overlay"
rm -rf config/includes.chroot/usr/share/borealis/themes/aurora-night \
       config/includes.chroot/usr/share/borealis/themes/glacier-light
cp -r themes/aurora-night themes/glacier-light \
      config/includes.chroot/usr/share/borealis/themes/

# --- 4. live-build config ------------------------------------------------------
say "Configuring live-build"
if [[ "${KEEP_CACHE:-0}" != "1" ]]; then
    lb clean --purge >/dev/null 2>&1 || true
fi

lb config \
    --architecture "$ARCH" \
    --distribution "$DIST" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --updates true \
    --security true \
    --backports true \
    --debian-installer none \
    --debian-installer-gui false \
    --memtest memtest86+ \
    --image-name "borealis-${ISO_VERSION}-${ARCH}" \
    --iso-application "Borealis Linux" \
    --iso-publisher "Borealis Linux Project; https://borealis-linux.example" \
    --iso-volume "BorealisLinux-${ISO_VERSION}" \
    --bootappend-live "boot=live components hostname=borealis username=borealis user-fullname=Borealis locales=en_US.UTF-8 keyboard-layouts=us quiet splash" \
    --linux-flavours amd64 \
    --mirror-bootstrap "$MIRROR" \
    --mirror-chroot "$MIRROR" \
    --mirror-binary "http://deb.debian.org/debian"

# lb config rewrites defaults; our overlay files under config/ remain in place.
chmod +x config/hooks/live/*.hook.chroot 2>/dev/null || true
# Executable bits for overlay scripts (git checkouts on Windows lose modes)
chmod +x config/includes.chroot/usr/bin/borealis-* 2>/dev/null || true
chmod 0440 config/includes.chroot/etc/sudoers.d/borealis-gameboost 2>/dev/null || true

# Inject version for os-release / branding used inside the image.
install -d config/includes.chroot/etc
if [[ ! -f config/includes.chroot/etc/borealis-release ]]; then
    printf 'Borealis Linux %s "Glacier" (Debian 12 base)\n' "$ISO_VERSION" \
        > config/includes.chroot/etc/borealis-release
fi

# --- 5. build ------------------------------------------------------------------
say "Building ISO (this takes 20–60 min depending on machine and network)"
lb build 2>&1 | tee "$LOG"

ISO="borealis-${ISO_VERSION}-${ARCH}.iso"
[[ -f "$ISO" ]] || die "lb build finished but $ISO not produced — inspect $LOG"

# --- 6. optional 32-bit UEFI injection (best-effort, off by default) ----------
if [[ "${ADD_EFI32:-0}" == "1" ]]; then
    say "Adding 32-bit UEFI bootloader (experimental)"
    scripts/add-efi32.sh "$ISO" "$ISO.efi32" && mv "$ISO.efi32" "$ISO" \
        || say "EFI32 injection skipped (non-fatal)"
fi

say "SUCCESS: $ISO"
say "Test it:  scripts/test-qemu-uefi.sh $ISO   |   scripts/test-qemu-bios.sh $ISO"
say "Follow TESTPLAN.md for the full verification matrix."
