# User creation. sudo group grants administration; root stays locked.
---
defaultGroups:
    - adm
    - cdrom
    - dip
    - lpadmin
    - plugdev
    - sudo
autologinGroup: autologin
doAutologin: false
setRootPassword: false
doReusePassword: true
sudoersConfigureWithGroup: sudo
userShell: /bin/bash
